In [1]:
import pandas as pd
import tensorflow as tf
data = pd.read_csv("C:/Users/QWERTY/Desktop/MachineLearning/creditcard.csv")

In [2]:
from sklearn.preprocessing import StandardScaler
data = data.drop(['Amount'],axis=1)
data = data.drop(['Time'],axis=1)
data.head()

V1        V2        V3        V4        V5        V6        V7  \
0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10  ...       V20       V21       V22       V23  \
0  0.098698  0.363787  0.090794  ...  0.251412 -0.018307  0.277838 -0.110474   
1  0.085102 -0.255425 -0.166974  ... -0.069083 -0.225775 -0.638672  0.101288   
2  0.247676 -1.514654  0.207643  ...  0.524980  0.247998  0.771679  0.909412   
3  0.377436 -1.387024 -0.054952  ... -0.208038 -0.108300  0.005274 -0.190321   
4 -0.270533  0.817739  0.753074  ...  0.408542 -0.009431  0.798278 -0.137458   

        V24       V25       V26       V27       V28  Class  
0  0.066928  0.128539 -0.189115  0.133558 -0.021053      0  
1 -0.339846  0.167170  0.125895 -0.008983  0.014724      0  
2 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752      0  
3 -1.175575  0.647376 -0.221929  0.062723  0.061458      0  
4  0.141267 -0.206010  0.502292  0.219422  0.215153      0  

[5 rows x 29 columns]

In [136]:
X = data.iloc[:, data.columns != 'Class']
y = data.iloc[:, data.columns == 'Class']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=0)

In [107]:
X_train.shape[0]

199364

In [108]:

input_shape = (29, 1)

In [137]:
X_test.shape[0]

85443

In [ ]:
###############################################################################################################################

In [109]:
#First of all, we will try to compile with
# 3 layers(relu, softmax, sigmoid) 
# with SGD optimizer
# loss = binary_crossentropy 

In [110]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense
# Initialising the ANN
model = Sequential()
# Adding the input layer and the first hidden layer
model.add(Dense(units =15 , kernel_initializer = 'uniform', activation = tf.nn.relu, input_dim = 28))
# Adding the second hidden layer
model.add(Dense(units = 15, kernel_initializer = 'uniform', activation = tf.nn.softmax))
# Adding the output layer
model.add(Dense(units = 1, kernel_initializer = 'uniform', activation = tf.nn.sigmoid))



In [77]:
# Compiling the ANN
model.compile(optimizer='sgd',  loss='binary_crossentropy',  metrics=['accuracy'])
model.fit(x=X_train,y=y_train, epochs=10)

Epoch 1/10
199364/199364 [==============================] - 17s 83us/step - loss: 0.0750 - accuracy: 0.9983
Epoch 2/10
199364/199364 [==============================] - 15s 77us/step - loss: 0.0194 - accuracy: 0.9983
Epoch 3/10
199364/199364 [==============================] - 17s 83us/step - loss: 0.0157 - accuracy: 0.9983
Epoch 4/10
199364/199364 [==============================] - 17s 84us/step - loss: 0.0144 - accuracy: 0.9983
Epoch 5/10
199364/199364 [==============================] - 16s 81us/step - loss: 0.0138 - accuracy: 0.9983
Epoch 6/10
199364/199364 [==============================] - 16s 78us/step - loss: 0.0134 - accuracy: 0.9983
Epoch 7/10
199364/199364 [==============================] - 16s 79us/step - loss: 0.0132 - accuracy: 0.9983
Epoch 8/10
199364/199364 [==============================] - 17s 84us/step - loss: 0.0131 - accuracy: 0.9983
Epoch 9/10
199364/199364 [==============================] - 17s 84us/step - loss: 0.0130 - accuracy: 0.9983
Epoch 10/10
199364/199364 [=

In [78]:
model.evaluate(X_test, y_test)

85443/85443 [==============================] - 4s 45us/step


[0.012820375721407169, 0.9982795715332031]

In [79]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[85296,     0],
       [  147,     0]], dtype=int64)

In [80]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.00      0.00      0.00       147

    accuracy                           1.00     85443
   macro avg       0.50      0.50      0.50     85443
weighted avg       1.00      1.00      1.00     85443



In [ ]:
# 3 layers(relu, softmax, sigmoid) 
# with ******ADAM****** optimizer
# loss = binary_crossentropy 

In [45]:
model.compile(optimizer='adam',  loss='binary_crossentropy',  metrics=['accuracy'])
model.fit(x=X_train,y=y_train, epochs=10)

Epoch 1/10
199364/199364 [==============================] - 18s 92us/step - loss: 0.0102 - accuracy: 0.9983
Epoch 2/10
199364/199364 [==============================] - 19s 96us/step - loss: 0.0068 - accuracy: 0.9983
Epoch 3/10
199364/199364 [==============================] - 19s 97us/step - loss: 0.0045 - accuracy: 0.9983
Epoch 4/10
199364/199364 [==============================] - 18s 92us/step - loss: 0.0033 - accuracy: 0.9991
Epoch 5/10
199364/199364 [==============================] - 18s 92us/step - loss: 0.0029 - accuracy: 0.9994
Epoch 6/10
199364/199364 [==============================] - 18s 92us/step - loss: 0.0029 - accuracy: 0.9994
Epoch 7/10
199364/199364 [==============================] - 19s 97us/step - loss: 0.0027 - accuracy: 0.9994
Epoch 8/10
199364/199364 [==============================] - 22s 109us/step - loss: 0.0026 - accuracy: 0.9994
Epoch 9/10
199364/199364 [==============================] - 18s 91us/step - loss: 0.0026 - accuracy: 0.9995
Epoch 10/10
199364/199364 [

In [46]:
model.evaluate(X_test, y_test)

85443/85443 [==============================] - 4s 45us/step


[0.0031733129818887337, 0.9994031190872192]

In [47]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[85273,    23],
       [   28,   119]], dtype=int64)

In [48]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.84      0.81      0.82       147

    accuracy                           1.00     85443
   macro avg       0.92      0.90      0.91     85443
weighted avg       1.00      1.00      1.00     85443



In [ ]:
# 3 layers(relu, softmax, sigmoid) 
# with ******RMSprop****** optimizer
# loss = binary_crossentropy 

In [49]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense
# Initialising the ANN
model = Sequential()
# Adding the input layer and the first hidden layer
model.add(Dense(units =15 , kernel_initializer = 'uniform', activation = tf.nn.relu, input_dim = 28))
# Adding the second hidden layer
model.add(Dense(units = 15, kernel_initializer = 'uniform', activation = tf.nn.softmax))
# Adding the output layer
model.add(Dense(units = 1, kernel_initializer = 'uniform', activation = tf.nn.sigmoid))

In [51]:
model.compile(optimizer='RMSprop',  loss='binary_crossentropy',  metrics=['accuracy'])
model.fit(x=X_train,y=y_train, epochs=10)

Epoch 1/10
199364/199364 [==============================] - 18s 88us/step - loss: 0.0706 - accuracy: 0.9978
Epoch 2/10
199364/199364 [==============================] - 21s 103us/step - loss: 0.0074 - accuracy: 0.9983
Epoch 3/10
199364/199364 [==============================] - 21s 104us/step - loss: 0.0057 - accuracy: 0.9983
Epoch 4/10
199364/199364 [==============================] - 19s 97us/step - loss: 0.0049 - accuracy: 0.9988
Epoch 5/10
199364/199364 [==============================] - 18s 93us/step - loss: 0.0047 - accuracy: 0.9994
Epoch 6/10
199364/199364 [==============================] - 18s 89us/step - loss: 0.0047 - accuracy: 0.9994
Epoch 7/10
199364/199364 [==============================] - 18s 90us/step - loss: 0.0050 - accuracy: 0.9994
Epoch 8/10
199364/199364 [==============================] - 17s 87us/step - loss: 0.0053 - accuracy: 0.9994
Epoch 9/10
199364/199364 [==============================] - 18s 89us/step - loss: 0.0053 - accuracy: 0.9994
Epoch 10/10
199364/199364 

In [52]:
model.evaluate(X_test, y_test)

85443/85443 [==============================] - 4s 42us/step


[0.0061716970506942035, 0.9993680119514465]

In [53]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[85273,    23],
       [   31,   116]], dtype=int64)

In [55]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.83      0.79      0.81       147

    accuracy                           1.00     85443
   macro avg       0.92      0.89      0.91     85443
weighted avg       1.00      1.00      1.00     85443



In [ ]:
# 3 layers(relu, softmax, sigmoid) 
# with ******ADAGRAD****** optimizer
# loss = binary_crossentropy 

In [60]:
model.compile(optimizer='Adagrad',  loss='binary_crossentropy',  metrics=['accuracy'])
model.fit(x=X_train,y=y_train, epochs=10)

Epoch 1/10
199364/199364 [==============================] - 16s 83us/step - loss: 0.0040 - accuracy: 0.9995
Epoch 2/10
199364/199364 [==============================] - 17s 84us/step - loss: 0.0037 - accuracy: 0.9994
Epoch 3/10
199364/199364 [==============================] - 18s 89us/step - loss: 0.0035 - accuracy: 0.9995
Epoch 4/10
199364/199364 [==============================] - 17s 84us/step - loss: 0.0033 - accuracy: 0.9994
Epoch 5/10
199364/199364 [==============================] - 16s 80us/step - loss: 0.0032 - accuracy: 0.9994
Epoch 6/10
199364/199364 [==============================] - 16s 81us/step - loss: 0.0031 - accuracy: 0.9995
Epoch 7/10
199364/199364 [==============================] - 17s 83us/step - loss: 0.0030 - accuracy: 0.9995
Epoch 8/10
199364/199364 [==============================] - 16s 80us/step - loss: 0.0029 - accuracy: 0.9994
Epoch 9/10
199364/199364 [==============================] - 16s 80us/step - loss: 0.0029 - accuracy: 0.9994
Epoch 10/10
199364/199364 [=

In [61]:
model.evaluate(X_test, y_test)

85443/85443 [==============================] - 4s 42us/step


[0.003660209756370661, 0.9993562698364258]

In [62]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[85269,    27],
       [   28,   119]], dtype=int64)

In [63]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.82      0.81      0.81       147

    accuracy                           1.00     85443
   macro avg       0.91      0.90      0.91     85443
weighted avg       1.00      1.00      1.00     85443



In [ ]:
# 3 layers(relu, softmax, sigmoid) 
# with ******ADADELTA****** optimizer
# loss = binary_crossentropy 

In [111]:
model.compile(optimizer='Adadelta',  loss='binary_crossentropy',  metrics=['accuracy'])
model.fit(x=X_train,y=y_train, epochs=10)

Epoch 1/10
199364/199364 [==============================] - 18s 91us/step - loss: 0.0489 - accuracy: 0.9983
Epoch 2/10
199364/199364 [==============================] - 18s 92us/step - loss: 0.0086 - accuracy: 0.9983
Epoch 3/10
199364/199364 [==============================] - 18s 89us/step - loss: 0.0072 - accuracy: 0.9983
Epoch 4/10
199364/199364 [==============================] - 20s 99us/step - loss: 0.0060 - accuracy: 0.9983
Epoch 5/10
199364/199364 [==============================] - 19s 95us/step - loss: 0.0051 - accuracy: 0.9983
Epoch 6/10
199364/199364 [==============================] - 19s 96us/step - loss: 0.0044 - accuracy: 0.9983
Epoch 7/10
199364/199364 [==============================] - 19s 97us/step - loss: 0.0039 - accuracy: 0.9987
Epoch 8/10
199364/199364 [==============================] - 19s 95us/step - loss: 0.0037 - accuracy: 0.9994
Epoch 9/10
199364/199364 [==============================] - 18s 92us/step - loss: 0.0036 - accuracy: 0.9994
Epoch 10/10
199364/199364 [=

In [112]:
model.evaluate(X_test, y_test)

85443/85443 [==============================] - 4s 41us/step


[0.0035755269752421976, 0.9993680119514465]

In [113]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[85274,    22],
       [   32,   115]], dtype=int64)

In [114]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.84      0.78      0.81       147

    accuracy                           1.00     85443
   macro avg       0.92      0.89      0.90     85443
weighted avg       1.00      1.00      1.00     85443



In [ ]:
# 3 layers(relu, softmax, sigmoid) 
# with ******NADAM****** optimizer
# loss = binary_crossentropy 

In [115]:
model.compile(optimizer='Nadam',  loss='binary_crossentropy',  metrics=['accuracy'])
model.fit(x=X_train,y=y_train, epochs=10)

Epoch 1/10
199364/199364 [==============================] - 22s 108us/step - loss: 0.0038 - accuracy: 0.9993
Epoch 2/10
199364/199364 [==============================] - 21s 106us/step - loss: 0.0036 - accuracy: 0.9993
Epoch 3/10
199364/199364 [==============================] - 20s 101us/step - loss: 0.0034 - accuracy: 0.9993
Epoch 4/10
199364/199364 [==============================] - 20s 102us/step - loss: 0.0032 - accuracy: 0.9993
Epoch 5/10
199364/199364 [==============================] - 21s 106us/step - loss: 0.0032 - accuracy: 0.9994
Epoch 6/10
199364/199364 [==============================] - 21s 103us/step - loss: 0.0031 - accuracy: 0.9993
Epoch 7/10
199364/199364 [==============================] - 21s 107us/step - loss: 0.0029 - accuracy: 0.9994
Epoch 8/10
199364/199364 [==============================] - 21s 103us/step - loss: 0.0028 - accuracy: 0.9994
Epoch 9/10
199364/199364 [==============================] - 23s 115us/step - loss: 0.0028 - accuracy: 0.9994
Epoch 10/10
199364/

In [116]:
model.evaluate(X_test, y_test)

85443/85443 [==============================] - 4s 44us/step


[0.0032321131882449266, 0.9994382262229919]

In [117]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[85274,    22],
       [   26,   121]], dtype=int64)

In [118]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.85      0.82      0.83       147

    accuracy                           1.00     85443
   macro avg       0.92      0.91      0.92     85443
weighted avg       1.00      1.00      1.00     85443



In [ ]:
#########################################################----PART TWO----#####################################################

In [ ]:
###############################################################################################################################

In [ ]:
###############################################################################################################################

In [ ]:
# above mentioned compilation illustrated us some good results (precision up 0.84, 0.83, 0.82). However what if we split dataset into 
#0.333 instead of 0.3  will we get better result?

In [138]:
X = data.iloc[:, data.columns != 'Class']
y = data.iloc[:, data.columns == 'Class']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.333, random_state=0)



In [139]:
X_train.shape[0]

189966

In [140]:

input_shape = (29, 1)

In [141]:
X_test.shape[0]

94841

In [142]:
# 3 layers(relu, softmax, sigmoid) 
# with ADAM optimizer
# loss = binary_crossentropy 
#Split data to 0.333

In [143]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense
# Initialising the ANN
model = Sequential()
# Adding the input layer and the first hidden layer
model.add(Dense(units =15 , kernel_initializer = 'uniform', activation = tf.nn.relu, input_dim = 28))
# Adding the second hidden layer
model.add(Dense(units = 15, kernel_initializer = 'uniform', activation = tf.nn.softmax))
# Adding the output layer
model.add(Dense(units = 1, kernel_initializer = 'uniform', activation = tf.nn.sigmoid))


In [144]:
# Compiling the ANN
model.compile(optimizer='sgd',  loss='binary_crossentropy',  metrics=['accuracy'])
model.fit(x=X_train,y=y_train, epochs=10)


Epoch 1/10
189966/189966 [==============================] - 14s 75us/step - loss: 0.0779 - accuracy: 0.9979
Epoch 2/10
189966/189966 [==============================] - 16s 84us/step - loss: 0.0199 - accuracy: 0.9983
Epoch 3/10
189966/189966 [==============================] - 14s 74us/step - loss: 0.0160 - accuracy: 0.9983
Epoch 4/10
189966/189966 [==============================] - 12s 64us/step - loss: 0.0145 - accuracy: 0.9983
Epoch 5/10
189966/189966 [==============================] - 12s 62us/step - loss: 0.0139 - accuracy: 0.9983
Epoch 6/10
189966/189966 [==============================] - 13s 66us/step - loss: 0.0135 - accuracy: 0.9983
Epoch 7/10
189966/189966 [==============================] - 13s 66us/step - loss: 0.0133 - accuracy: 0.9983
Epoch 8/10
189966/189966 [==============================] - 13s 67us/step - loss: 0.0131 - accuracy: 0.9983
Epoch 9/10
189966/189966 [==============================] - 13s 68us/step - loss: 0.0130 - accuracy: 0.9983
Epoch 10/10
189966/189966 [=

In [145]:
model.evaluate(X_test, y_test)

94841/94841 [==============================] - 4s 47us/step


[0.012832320326538143, 0.9982813596725464]

In [146]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)


array([[94678,     0],
       [  163,     0]], dtype=int64)

In [147]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     94678
           1       0.00      0.00      0.00       163

    accuracy                           1.00     94841
   macro avg       0.50      0.50      0.50     94841
weighted avg       1.00      1.00      1.00     94841



In [148]:
#With SGD optimizer,  it remains the same...
#Let's see what will give compilations with other optimizers

In [149]:
# 3 layers(relu, softmax, sigmoid) 
# with ADAM optimizer
# loss = binary_crossentropy 
#Split data to 0.333

In [150]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense
# Initialising the ANN
model = Sequential()
# Adding the input layer and the first hidden layer
model.add(Dense(units =15 , kernel_initializer = 'uniform', activation = tf.nn.relu, input_dim = 28))
# Adding the second hidden layer
model.add(Dense(units = 15, kernel_initializer = 'uniform', activation = tf.nn.softmax))
# Adding the output layer
model.add(Dense(units = 1, kernel_initializer = 'uniform', activation = tf.nn.sigmoid))


In [151]:
model.compile(optimizer='adam',  loss='binary_crossentropy',  metrics=['accuracy'])
model.fit(x=X_train,y=y_train, epochs=10)

Epoch 1/10
189966/189966 [==============================] - 21s 109us/step - loss: 0.0856 - accuracy: 0.9983
Epoch 2/10
189966/189966 [==============================] - 19s 99us/step - loss: 0.0070 - accuracy: 0.9983
Epoch 3/10
189966/189966 [==============================] - 18s 95us/step - loss: 0.0043 - accuracy: 0.9984
Epoch 4/10
189966/189966 [==============================] - 18s 93us/step - loss: 0.0034 - accuracy: 0.9994
Epoch 5/10
189966/189966 [==============================] - 18s 94us/step - loss: 0.0031 - accuracy: 0.9994
Epoch 6/10
189966/189966 [==============================] - 18s 93us/step - loss: 0.0031 - accuracy: 0.9994
Epoch 7/10
189966/189966 [==============================] - 18s 94us/step - loss: 0.0030 - accuracy: 0.9994
Epoch 8/10
189966/189966 [==============================] - 18s 94us/step - loss: 0.0028 - accuracy: 0.9995
Epoch 9/10
189966/189966 [==============================] - 18s 93us/step - loss: 0.0028 - accuracy: 0.9995
Epoch 10/10
189966/189966 [

In [152]:
model.evaluate(X_test, y_test)

94841/94841 [==============================] - 4s 41us/step


[0.003237746490512764, 0.9994411468505859]

In [153]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[94655,    23],
       [   30,   133]], dtype=int64)

In [154]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     94678
           1       0.85      0.82      0.83       163

    accuracy                           1.00     94841
   macro avg       0.93      0.91      0.92     94841
weighted avg       1.00      1.00      1.00     94841



In [ ]:
#As it can be seen we we splitted data set to 0.3 we precision was 0.84.
#But when we splitted to 0.333 we increased  precision to 0.85.
#Let's see how compilations with another optimizers will show...

In [ ]:
# 3 layers(relu, softmax, sigmoid) 
# with RMSprop optimizer
# loss = binary_crossentropy 
#Split data to 0.333

In [ ]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense
# Initialising the ANN
model = Sequential()
# Adding the input layer and the first hidden layer
model.add(Dense(units =15 , kernel_initializer = 'uniform', activation = tf.nn.relu, input_dim = 28))
# Adding the second hidden layer
model.add(Dense(units = 15, kernel_initializer = 'uniform', activation = tf.nn.softmax))
# Adding the output layer
model.add(Dense(units = 1, kernel_initializer = 'uniform', activation = tf.nn.sigmoid))

In [155]:
model.compile(optimizer='RMSprop',  loss='binary_crossentropy',  metrics=['accuracy'])
model.fit(x=X_train,y=y_train, epochs=10)


Epoch 1/10
189966/189966 [==============================] - 16s 85us/step - loss: 0.0039 - accuracy: 0.9994
Epoch 2/10
189966/189966 [==============================] - 16s 84us/step - loss: 0.0043 - accuracy: 0.9994
Epoch 3/10
189966/189966 [==============================] - 16s 85us/step - loss: 0.0045 - accuracy: 0.9994
Epoch 4/10
189966/189966 [==============================] - 16s 86us/step - loss: 0.0046 - accuracy: 0.9994
Epoch 5/10
189966/189966 [==============================] - 17s 88us/step - loss: 0.0048 - accuracy: 0.9994
Epoch 6/10
189966/189966 [==============================] - 17s 88us/step - loss: 0.0048 - accuracy: 0.9994
Epoch 7/10
189966/189966 [==============================] - 17s 87us/step - loss: 0.0049 - accuracy: 0.9995
Epoch 8/10
189966/189966 [==============================] - 17s 90us/step - loss: 0.0053 - accuracy: 0.9994
Epoch 9/10
189966/189966 [==============================] - 17s 87us/step - loss: 0.0051 - accuracy: 0.9995
Epoch 10/10
189966/189966 [=

In [156]:
model.evaluate(X_test, y_test)


94841/94841 [==============================] - 4s 44us/step


[0.00615121423626668, 0.9993779063224792]

In [160]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)


array([[94647,    31],
       [   28,   135]], dtype=int64)

In [161]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     94678
           1       0.81      0.83      0.82       163

    accuracy                           1.00     94841
   macro avg       0.91      0.91      0.91     94841
weighted avg       1.00      1.00      1.00     94841



In [162]:
#As it can be seen we we splitted data set to 0.3 our precision value was 0.83. 
#But when we splitted to 0.333 we increased  precision to 0.86.
#Let's see how compilations with another optimizers will show...

In [163]:
# 3 layers(relu, softmax, sigmoid) 
# with Adagrad optimizer
# loss = binary_crossentropy 
#Split data to 0.333

In [ ]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense
# Initialising the ANN
model = Sequential()
# Adding the input layer and the first hidden layer
model.add(Dense(units =15 , kernel_initializer = 'uniform', activation = tf.nn.relu, input_dim = 28))
# Adding the second hidden layer
model.add(Dense(units = 15, kernel_initializer = 'uniform', activation = tf.nn.softmax))
# Adding the output layer
model.add(Dense(units = 1, kernel_initializer = 'uniform', activation = tf.nn.sigmoid))

In [102]:
model.compile(optimizer='Adagrad',  loss='binary_crossentropy',  metrics=['accuracy'])
model.fit(x=X_train,y=y_train, epochs=10)


Epoch 1/10
189966/189966 [==============================] - 14s 73us/step - loss: 0.0043 - accuracy: 0.9995
Epoch 2/10
189966/189966 [==============================] - 14s 73us/step - loss: 0.0037 - accuracy: 0.9995
Epoch 3/10
189966/189966 [==============================] - 14s 75us/step - loss: 0.0037 - accuracy: 0.9995
Epoch 4/10
189966/189966 [==============================] - 14s 73us/step - loss: 0.0036 - accuracy: 0.9995
Epoch 5/10
189966/189966 [==============================] - 14s 75us/step - loss: 0.0036 - accuracy: 0.9995
Epoch 6/10
189966/189966 [==============================] - 15s 81us/step - loss: 0.0035 - accuracy: 0.9995
Epoch 7/10
189966/189966 [==============================] - 16s 82us/step - loss: 0.0035 - accuracy: 0.9995
Epoch 8/10
189966/189966 [==============================] - 16s 83us/step - loss: 0.0035 - accuracy: 0.9995
Epoch 9/10
189966/189966 [==============================] - 16s 85us/step - loss: 0.0035 - accuracy: 0.9995
Epoch 10/10
189966/189966 [=

In [103]:
model.evaluate(X_test, y_test)


94841/94841 [==============================] - 4s 46us/step


[0.005033404198799858, 0.9993990063667297]

In [104]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)


array([[94658,    20],
       [   37,   126]], dtype=int64)

In [105]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     94678
           1       0.86      0.77      0.82       163

    accuracy                           1.00     94841
   macro avg       0.93      0.89      0.91     94841
weighted avg       1.00      1.00      1.00     94841



In [ ]:
#As it can be seen we we splitted data set to 0.3 we our precision value was 0.82.
#But when we splitted to 0.333 we increased  precision to 0.86.
#Let's see how compilations with another optimizers will tell...

In [ ]:
# 3 layers(relu, softmax, sigmoid) 
# with ******ADADELTA****** optimizer
# loss = binary_crossentropy  
#Split data to 0.333

In [ ]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense
# Initialising the ANN
model = Sequential()
# Adding the input layer and the first hidden layer
model.add(Dense(units =15 , kernel_initializer = 'uniform', activation = tf.nn.relu, input_dim = 28))
# Adding the second hidden layer
model.add(Dense(units = 15, kernel_initializer = 'uniform', activation = tf.nn.softmax))
# Adding the output layer
model.add(Dense(units = 1, kernel_initializer = 'uniform', activation = tf.nn.sigmoid))

In [124]:
model.compile(optimizer='Adadelta',  loss='binary_crossentropy',  metrics=['accuracy'])
model.fit(x=X_train,y=y_train, epochs=10)


Epoch 1/10
189966/189966 [==============================] - 18s 97us/step - loss: 0.0514 - accuracy: 0.9983
Epoch 2/10
189966/189966 [==============================] - 19s 98us/step - loss: 0.0083 - accuracy: 0.9983
Epoch 3/10
189966/189966 [==============================] - 19s 100us/step - loss: 0.0070 - accuracy: 0.9983
Epoch 4/10
189966/189966 [==============================] - 18s 95us/step - loss: 0.0059 - accuracy: 0.9983
Epoch 5/10
189966/189966 [==============================] - 19s 98us/step - loss: 0.0050 - accuracy: 0.9983
Epoch 6/10
189966/189966 [==============================] - 18s 92us/step - loss: 0.0044 - accuracy: 0.9983
Epoch 7/10
189966/189966 [==============================] - 18s 95us/step - loss: 0.0040 - accuracy: 0.9987
Epoch 8/10
189966/189966 [==============================] - 18s 95us/step - loss: 0.0037 - accuracy: 0.9994
Epoch 9/10
189966/189966 [==============================] - 18s 96us/step - loss: 0.0035 - accuracy: 0.9994
Epoch 10/10
189966/189966 [

In [125]:
model.evaluate(X_test, y_test)

94841/94841 [==============================] - 4s 45us/step


[0.0033991166091827175, 0.9993779063224792]

In [126]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)


array([[94651,    27],
       [   32,   131]], dtype=int64)

In [127]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))



              precision    recall  f1-score   support

           0       1.00      1.00      1.00     94678
           1       0.83      0.80      0.82       163

    accuracy                           1.00     94841
   macro avg       0.91      0.90      0.91     94841
weighted avg       1.00      1.00      1.00     94841



In [ ]:
# 3 layers(relu, softmax, sigmoid) 
# with ******NADAM****** optimizer
# loss = binary_crossentropy 


In [128]:
model.compile(optimizer='Nadam',  loss='binary_crossentropy',  metrics=['accuracy'])
model.fit(x=X_train,y=y_train, epochs=10)


Epoch 1/10
189966/189966 [==============================] - 18s 93us/step - loss: 0.0034 - accuracy: 0.9993
Epoch 2/10
189966/189966 [==============================] - 17s 92us/step - loss: 0.0034 - accuracy: 0.9993
Epoch 3/10
189966/189966 [==============================] - 18s 94us/step - loss: 0.0032 - accuracy: 0.9993
Epoch 4/10
189966/189966 [==============================] - 19s 98us/step - loss: 0.0031 - accuracy: 0.9993
Epoch 5/10
189966/189966 [==============================] - 19s 102us/step - loss: 0.0031 - accuracy: 0.9993
Epoch 6/10
189966/189966 [==============================] - 19s 101us/step - loss: 0.0030 - accuracy: 0.9994
Epoch 7/10
189966/189966 [==============================] - 19s 102us/step - loss: 0.0029 - accuracy: 0.9994
Epoch 8/10
189966/189966 [==============================] - 19s 103us/step - loss: 0.0029 - accuracy: 0.9994
Epoch 9/10
189966/189966 [==============================] - 19s 99us/step - loss: 0.0030 - accuracy: 0.9994
Epoch 10/10
189966/18996

In [129]:
model.evaluate(X_test, y_test)


94841/94841 [==============================] - 5s 52us/step


[0.0034073854739274058, 0.9992724657058716]

In [130]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)


array([[94636,    42],
       [   27,   136]], dtype=int64)

In [131]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))



              precision    recall  f1-score   support

           0       1.00      1.00      1.00     94678
           1       0.76      0.83      0.80       163

    accuracy                           1.00     94841
   macro avg       0.88      0.92      0.90     94841
weighted avg       1.00      1.00      1.00     94841

