# Library

In [4]:
import pandas as pd
import tensorflow as tf
from tensorflow import keras
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense




Using TensorFlow backend.


# DataSet 

In [6]:
my_data = pd.read_csv("creditcard.csv")
# So first of all let's get introduced with out dataset
my_data.head()


Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [7]:
#Next we will expand the view, by seeing the shape of our data
my_data.shape

(284807, 31)

In [ ]:
#From here we can see that we must to deal with 31 columns and 284807 rows

In [8]:
#Then we may want to see how many subclasses we have in our classes 
my_data['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [ ]:
#Here as it can be seen, we are facing with some really unbalanced dataset.
#As we have been warned in the problem itself, where it said that only 0.175% of 
#transactions were fradulent, which is very low, and for a machine it is very hard to
#recognise the 0's and 1's in our target(which is 'Class' column)

# Prologue

In [ ]:
# In the begining, the unbalanced dataset was a real pain for us. So, we decided
# to work with this raw, unsorted, unbalanced dataset despite the fact,
# that because of it's unbalanceness it always predicted with 0.9983 accuracy, no matter what kind of model was. 
# However, we saw a light at the end of a tunnel, when got to the point when we checked 
# our confusion matrix and classification report...

In [ ]:
# But first let us see the WORK that has been done over UNBALANCED DATASET...

# Neural Network Compiled Upon Unbalanced Dataset 

In [9]:
import pandas as pd
import tensorflow as tf
data = pd.read_csv("C:/Users/QWERTY/Desktop/MachineLearning/creditcard.csv")
data = data.drop(['Amount'],axis=1)
data = data.drop(['Time'],axis=1)
data.head()

V1        V2        V3        V4        V5        V6        V7  \
0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10  ...       V20       V21       V22       V23  \
0  0.098698  0.363787  0.090794  ...  0.251412 -0.018307  0.277838 -0.110474   
1  0.085102 -0.255425 -0.166974  ... -0.069083 -0.225775 -0.638672  0.101288   
2  0.247676 -1.514654  0.207643  ...  0.524980  0.247998  0.771679  0.909412   
3  0.377436 -1.387024 -0.054952  ... -0.208038 -0.108300  0.005274 -0.190321   
4 -0.270533  0.817739  0.753074  ...  0.408542 -0.009431  0.798278 -0.137458   

        V24       V25       V26       V27       V28  Class  
0  0.066928  0.128539 -0.189115  0.133558 -0.021053      0  
1 -0.339846  0.167170  0.125895 -0.008983  0.014724      0  
2 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752      0  
3 -1.175575  0.647376 -0.221929  0.062723  0.061458      0  
4  0.141267 -0.206010  0.502292  0.219422  0.215153      0  

[5 rows x 29 columns]

In [10]:
X = data.iloc[:, data.columns != 'Class']
y = data.iloc[:, data.columns == 'Class']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=0)

In [11]:
X_train.shape[0]

199364

In [12]:
X_test.shape[0]

85443

In [13]:
input_shape = (29, 1)

In [22]:
# Initialising the ANN
model = Sequential()
# Adding the input layer and the first hidden layer
model.add(Dense(units =512 , kernel_initializer = 'uniform', activation = tf.nn.relu, input_dim = 28))
# Adding the second hidden layer
model.add(Dense(units =256 , kernel_initializer = 'uniform', activation = tf.nn.softmax))
# Adding the third hidden layer
model.add(Dense(units = 128, kernel_initializer = 'uniform', activation = tf.nn.relu))
# Adding the output layer
model.add(Dense(units = 1, kernel_initializer = 'uniform', activation = tf.nn.sigmoid))

In [23]:
# Compiling the ANN
model.compile(optimizer='sgd',  loss='binary_crossentropy',  metrics=['accuracy'])
model.fit(x=X_train,y=y_train, epochs=10)

Epoch 1/10
199364/199364 [==============================] - 17s 83us/step - loss: 0.0596 - accuracy: 0.9981
Epoch 2/10
199364/199364 [==============================] - 15s 77us/step - loss: 0.0133 - accuracy: 0.9983
Epoch 3/10
199364/199364 [==============================] - 15s 78us/step - loss: 0.0128 - accuracy: 0.9983
Epoch 4/10
199364/199364 [==============================] - 16s 79us/step - loss: 0.0127 - accuracy: 0.9983
Epoch 5/10
199364/199364 [==============================] - 15s 77us/step - loss: 0.0127 - accuracy: 0.9983
Epoch 6/10
199364/199364 [==============================] - 17s 84us/step - loss: 0.0127 - accuracy: 0.9983
Epoch 7/10
199364/199364 [==============================] - 16s 81us/step - loss: 0.0127 - accuracy: 0.9983
Epoch 8/10
199364/199364 [==============================] - 17s 87us/step - loss: 0.0127 - accuracy: 0.9983
Epoch 9/10
199364/199364 [==============================] - 17s 87us/step - loss: 0.0127 - accuracy: 0.9983
Epoch 10/10
199364/199364 [=

In [24]:
model.evaluate(X_test, y_test)

85443/85443 [==============================] - 3s 40us/step


[0.012665891082583062, 0.9982795715332031]

In [25]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)
confusion_matrix(y_test, y_pred)

array([[85296,     0],
       [  147,     0]], dtype=int64)

In [26]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.00      0.00      0.00       147

    accuracy                           1.00     85443
   macro avg       0.50      0.50      0.50     85443
weighted avg       1.00      1.00      1.00     85443



In [40]:
# Initialising the ANN
model = Sequential()
# Adding the input layer and the first hidden layer
model.add(Dense(units =512 , kernel_initializer = 'uniform', activation = tf.nn.relu, input_dim = 28))
# Adding the second hidden layer
model.add(Dense(units =256 , kernel_initializer = 'uniform', activation = tf.nn.softmax))
# Adding the third hidden layer
model.add(Dense(units = 128, kernel_initializer = 'uniform', activation = tf.nn.relu))
# Adding the output layer
model.add(Dense(units = 1, kernel_initializer = 'uniform', activation = tf.nn.sigmoid))

In [41]:
model.compile(optimizer='adam',  loss='binary_crossentropy',  metrics=['accuracy'])
model.fit(x=X_train,y=y_train, epochs=10)

Epoch 1/10
199364/199364 [==============================] - 20s 98us/step - loss: 0.0121 - accuracy: 0.9985
Epoch 2/10
199364/199364 [==============================] - 20s 101us/step - loss: 0.0040 - accuracy: 0.9993
Epoch 3/10
199364/199364 [==============================] - 20s 99us/step - loss: 0.0036 - accuracy: 0.9993
Epoch 4/10
199364/199364 [==============================] - 21s 107us/step - loss: 0.0037 - accuracy: 0.9993
Epoch 5/10
199364/199364 [==============================] - 23s 113us/step - loss: 0.0034 - accuracy: 0.9994
Epoch 6/10
199364/199364 [==============================] - 21s 103us/step - loss: 0.0034 - accuracy: 0.9994
Epoch 7/10
199364/199364 [==============================] - 21s 108us/step - loss: 0.0038 - accuracy: 0.9994
Epoch 8/10
199364/199364 [==============================] - 22s 109us/step - loss: 0.0039 - accuracy: 0.9993
Epoch 9/10
199364/199364 [==============================] - 19s 97us/step - loss: 0.0039 - accuracy: 0.9993
Epoch 10/10
199364/199

In [42]:
model.evaluate(X_test, y_test)

85443/85443 [==============================] - 4s 44us/step


[0.004007419937537827, 0.9994148015975952]

In [43]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)
confusion_matrix(y_test, y_pred)

array([[85277,    19],
       [   31,   116]], dtype=int64)

In [44]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.86      0.79      0.82       147

    accuracy                           1.00     85443
   macro avg       0.93      0.89      0.91     85443
weighted avg       1.00      1.00      1.00     85443



In [45]:
# Initialising the ANN
model = Sequential()
# Adding the input layer and the first hidden layer
model.add(Dense(units =512 , kernel_initializer = 'uniform', activation = tf.nn.relu, input_dim = 28))
# Adding the second hidden layer
model.add(Dense(units =256 , kernel_initializer = 'uniform', activation = tf.nn.softmax))
# Adding the third hidden layer
model.add(Dense(units = 128, kernel_initializer = 'uniform', activation = tf.nn.relu))
# Adding the output layer
model.add(Dense(units = 1, kernel_initializer = 'uniform', activation = tf.nn.sigmoid))

In [46]:
model.compile(optimizer='RMSprop',  loss='binary_crossentropy',  metrics=['accuracy'])
model.fit(x=X_train,y=y_train, epochs=10)

Epoch 1/10
199364/199364 [==============================] - 19s 97us/step - loss: 0.0130 - accuracy: 0.9989
Epoch 2/10
199364/199364 [==============================] - 18s 93us/step - loss: 0.0058 - accuracy: 0.9994
Epoch 3/10
199364/199364 [==============================] - 17s 84us/step - loss: 0.0058 - accuracy: 0.9993
Epoch 4/10
199364/199364 [==============================] - 17s 84us/step - loss: 0.0064 - accuracy: 0.9992
Epoch 5/10
199364/199364 [==============================] - 17s 83us/step - loss: 0.0068 - accuracy: 0.9992
Epoch 6/10
199364/199364 [==============================] - 17s 87us/step - loss: 0.0069 - accuracy: 0.9993
Epoch 7/10
199364/199364 [==============================] - 18s 90us/step - loss: 0.0069 - accuracy: 0.9992
Epoch 8/10
199364/199364 [==============================] - 17s 84us/step - loss: 0.0064 - accuracy: 0.9993
Epoch 9/10
199364/199364 [==============================] - 17s 84us/step - loss: 0.0060 - accuracy: 0.9992
Epoch 10/10
199364/199364 [=

In [47]:
model.evaluate(X_test, y_test)

85443/85443 [==============================] - 4s 44us/step


[0.006189566212638332, 0.9993796944618225]

In [48]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)
confusion_matrix(y_test, y_pred)

array([[85273,    23],
       [   30,   117]], dtype=int64)

In [49]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.84      0.80      0.82       147

    accuracy                           1.00     85443
   macro avg       0.92      0.90      0.91     85443
weighted avg       1.00      1.00      1.00     85443



In [50]:
# Initialising the ANN
model = Sequential()
# Adding the input layer and the first hidden layer
model.add(Dense(units =512 , kernel_initializer = 'uniform', activation = tf.nn.relu, input_dim = 28))
# Adding the second hidden layer
model.add(Dense(units =256 , kernel_initializer = 'uniform', activation = tf.nn.softmax))
# Adding the third hidden layer
model.add(Dense(units = 128, kernel_initializer = 'uniform', activation = tf.nn.relu))
# Adding the output layer
model.add(Dense(units = 1, kernel_initializer = 'uniform', activation = tf.nn.sigmoid))

In [51]:
model.compile(optimizer='Adagrad',  loss='binary_crossentropy',  metrics=['accuracy'])
model.fit(x=X_train,y=y_train, epochs=10)

Epoch 1/10
199364/199364 [==============================] - 17s 87us/step - loss: 0.0098 - accuracy: 0.9981
Epoch 2/10
199364/199364 [==============================] - 15s 77us/step - loss: 0.0036 - accuracy: 0.9983
Epoch 3/10
199364/199364 [==============================] - 16s 78us/step - loss: 0.0033 - accuracy: 0.9983
Epoch 4/10
199364/199364 [==============================] - 15s 76us/step - loss: 0.0031 - accuracy: 0.9983
Epoch 5/10
199364/199364 [==============================] - 15s 76us/step - loss: 0.0030 - accuracy: 0.9983
Epoch 6/10
199364/199364 [==============================] - 16s 82us/step - loss: 0.0028 - accuracy: 0.9984
Epoch 7/10
199364/199364 [==============================] - 16s 82us/step - loss: 0.0027 - accuracy: 0.9995
Epoch 8/10
199364/199364 [==============================] - 16s 82us/step - loss: 0.0026 - accuracy: 0.9995
Epoch 9/10
199364/199364 [==============================] - 17s 85us/step - loss: 0.0025 - accuracy: 0.9995
Epoch 10/10
199364/199364 [=

In [52]:
model.evaluate(X_test, y_test)

85443/85443 [==============================] - 4s 46us/step


[0.0032363450469072266, 0.999426543712616]

In [53]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)
confusion_matrix(y_test, y_pred)

array([[85278,    18],
       [   31,   116]], dtype=int64)

In [54]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.87      0.79      0.83       147

    accuracy                           1.00     85443
   macro avg       0.93      0.89      0.91     85443
weighted avg       1.00      1.00      1.00     85443



In [55]:
# Initialising the ANN
model = Sequential()
# Adding the input layer and the first hidden layer
model.add(Dense(units =512 , kernel_initializer = 'uniform', activation = tf.nn.relu, input_dim = 28))
# Adding the second hidden layer
model.add(Dense(units =256 , kernel_initializer = 'uniform', activation = tf.nn.softmax))
# Adding the third hidden layer
model.add(Dense(units = 128, kernel_initializer = 'uniform', activation = tf.nn.relu))
# Adding the output layer
model.add(Dense(units = 1, kernel_initializer = 'uniform', activation = tf.nn.sigmoid))

In [56]:
model.compile(optimizer='Adadelta',  loss='binary_crossentropy',  metrics=['accuracy'])
model.fit(x=X_train,y=y_train, epochs=10)

Epoch 1/10
199364/199364 [==============================] - 21s 105us/step - loss: 0.0128 - accuracy: 0.9984
Epoch 2/10
199364/199364 [==============================] - 19s 93us/step - loss: 0.0037 - accuracy: 0.9993
Epoch 3/10
199364/199364 [==============================] - 18s 93us/step - loss: 0.0037 - accuracy: 0.9993
Epoch 4/10
199364/199364 [==============================] - 19s 93us/step - loss: 0.0037 - accuracy: 0.9994
Epoch 5/10
199364/199364 [==============================] - 18s 93us/step - loss: 0.0035 - accuracy: 0.9994
Epoch 6/10
199364/199364 [==============================] - 19s 93us/step - loss: 0.0035 - accuracy: 0.9994
Epoch 7/10
199364/199364 [==============================] - 18s 92us/step - loss: 0.0035 - accuracy: 0.9994
Epoch 8/10
199364/199364 [==============================] - 18s 92us/step - loss: 0.0035 - accuracy: 0.9994
Epoch 9/10
199364/199364 [==============================] - 19s 95us/step - loss: 0.0035 - accuracy: 0.9994
Epoch 10/10
199364/199364 [

In [57]:
model.evaluate(X_test, y_test)

85443/85443 [==============================] - 4s 42us/step


[0.0034966547360781803, 0.9994382262229919]

In [58]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)
confusion_matrix(y_test, y_pred)

array([[85276,    20],
       [   28,   119]], dtype=int64)

In [59]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.86      0.81      0.83       147

    accuracy                           1.00     85443
   macro avg       0.93      0.90      0.92     85443
weighted avg       1.00      1.00      1.00     85443



In [60]:
# Initialising the ANN
model = Sequential()
# Adding the input layer and the first hidden layer
model.add(Dense(units =512 , kernel_initializer = 'uniform', activation = tf.nn.relu, input_dim = 28))
# Adding the second hidden layer
model.add(Dense(units =256 , kernel_initializer = 'uniform', activation = tf.nn.softmax))
# Adding the third hidden layer
model.add(Dense(units = 128, kernel_initializer = 'uniform', activation = tf.nn.relu))
# Adding the output layer
model.add(Dense(units = 1, kernel_initializer = 'uniform', activation = tf.nn.sigmoid))

In [61]:
model.compile(optimizer='Nadam',  loss='binary_crossentropy',  metrics=['accuracy'])
model.fit(x=X_train,y=y_train, epochs=10)

Epoch 1/10
199364/199364 [==============================] - 23s 113us/step - loss: 0.0087 - accuracy: 0.9988
Epoch 2/10
199364/199364 [==============================] - 23s 114us/step - loss: 0.0043 - accuracy: 0.9993
Epoch 3/10
199364/199364 [==============================] - 22s 110us/step - loss: 0.0039 - accuracy: 0.9994
Epoch 4/10
199364/199364 [==============================] - 22s 108us/step - loss: 0.0039 - accuracy: 0.9994
Epoch 5/10
199364/199364 [==============================] - 22s 111us/step - loss: 0.0039 - accuracy: 0.9994
Epoch 6/10
199364/199364 [==============================] - 23s 115us/step - loss: 0.0039 - accuracy: 0.9994
Epoch 7/10
199364/199364 [==============================] - 21s 107us/step - loss: 0.0039 - accuracy: 0.9994
Epoch 8/10
199364/199364 [==============================] - 21s 108us/step - loss: 0.0039 - accuracy: 0.9994
Epoch 9/10
199364/199364 [==============================] - 22s 110us/step - loss: 0.0039 - accuracy: 0.9994
Epoch 10/10
199364/

In [62]:
model.evaluate(X_test, y_test)

85443/85443 [==============================] - 3s 39us/step


[0.0038799752295907357, 0.9993796944618225]

In [63]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)
confusion_matrix(y_test, y_pred)

array([[85273,    23],
       [   30,   117]], dtype=int64)

In [64]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.84      0.80      0.82       147

    accuracy                           1.00     85443
   macro avg       0.92      0.90      0.91     85443
weighted avg       1.00      1.00      1.00     85443



# Conclusion of Built Model Upon Unbalanced DataSet 

In [ ]:
As a conclusion, 
optimizer  | precision | recall
-----------|-----------|-------
SGD        |0.0        |0.0
Adam       |0.86       |0.79
RMSprop    |0.84       |0.80
Adagrad    |0.87       |0.79    ------> Winner!!!
Adadelta   |0.86       |0.81   
Nadam      |0.84       |0.80

# Since we found out that the best optimizer is actually Adagrad then ...

# Balancing DataSet

In [5]:
my_data = pd.read_csv("C:/Users/QWERTY/Desktop/MachineLearning/creditcard.csv")
# So first of all let's get introduced with out dataset
my_data.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [6]:
NotFraud = my_data[my_data['Class']==0]
IsFraud = my_data[my_data['Class']==1]

In [7]:
NotFraud.shape

(284315, 31)

In [8]:
IsFraud.shape

(492, 31)

In [9]:
NotFraud = NotFraud.sample(IsFraud.shape[0])

In [10]:
NotFraud.shape, IsFraud.shape

((492, 31), (492, 31))

In [11]:
my_balanced_data = IsFraud.append(NotFraud, ignore_index = True)
my_balanced_data

Time        V1        V2        V3        V4        V5        V6  \
0       406.0 -2.312227  1.951992 -1.609851  3.997906 -0.522188 -1.426545   
1       472.0 -3.043541 -3.157307  1.088463  2.288644  1.359805 -1.064823   
2      4462.0 -2.303350  1.759247 -0.359745  2.330243 -0.821628 -0.075788   
3      6986.0 -4.397974  1.358367 -2.592844  2.679787 -1.128131 -1.706536   
4      7519.0  1.234235  3.019740 -4.304597  4.732795  3.624201 -1.357746   
..        ...       ...       ...       ...       ...       ...       ...   
979  139073.0 -2.126542  2.761755 -1.147091 -0.956272  0.200288 -1.365569   
980  100386.0  1.921557  0.058964 -1.496580  1.414390  0.622377 -0.392203   
981  132024.0 -0.092369  0.036454 -0.726424  0.098719 -0.209112 -0.719427   
982   83208.0 -1.249951  0.597260  2.107010  0.849651 -0.386360  2.112547   
983   19514.0  1.184871 -0.408943  0.986772 -0.550467 -1.070345 -0.333586   

           V7        V8        V9  ...       V21       V22       V23  \
0   -2.537387  1.391657 -2.770089  ...  0.517232 -0.035049 -0.465211   
1    0.325574 -0.067794 -0.270953  ...  0.661696  0.435477  1.375966   
2    0.562320 -0.399147 -0.238253  ... -0.294166 -0.932391  0.172726   
3   -3.496197 -0.248778 -0.247768  ...  0.573574  0.176968 -0.436207   
4    1.713445 -0.496358 -1.282858  ... -0.379068 -0.704181 -0.656805   
..        ...       ...       ...  ...       ...       ...       ...   
979  1.048383 -0.254260  1.731266  ...  0.073958  1.204265  0.001905   
980  0.347012 -0.297086  1.623498  ... -0.253233 -0.533454  0.128717   
981  1.297252 -0.889625 -1.562701  ...  0.238638  1.239931 -0.283594   
982 -0.347288  1.214044 -0.155924  ...  0.252319  0.673682  0.114307   
983 -0.812951  0.092515  3.289301  ... -0.142908  0.035093  0.010972   

          V24       V25       V26       V27       V28  Amount  Class  
0    0.320198  0.044519  0.177840  0.261145 -0.143276    0.00      1  
1   -0.293803  0.279798 -0.145362 -0.252773  0.035764  529.00      1  
2   -0.087330 -0.156114 -0.542628  0.039566 -0.153029  239.93      1  
3   -0.053502  0.252405 -0.657488 -0.827136  0.849573   59.00      1  
4   -1.632653  1.488901  0.566797 -0.010016  0.146793    1.00      1  
..        ...       ...       ...       ...       ...     ...    ...  
979  0.003249 -0.221711 -0.174085  1.579898  0.921772    0.79      0  
980  0.305456  0.136793 -0.789964 -0.046910 -0.043025   72.65      0  
981 -0.011890 -0.744348  0.265810  0.032133 -0.034673  225.08      0  
982 -0.990864 -0.067631 -0.135208  0.037607  0.020324   94.19      0  
983  0.003618  0.358243 -0.692482  0.073234  0.024695   11.85      0  

[984 rows x 31 columns]

In [12]:
import pandas as pd
import tensorflow as tf
my_balanced_data =my_balanced_data.drop(['Amount'],axis=1)
my_balanced_data = my_balanced_data.drop(['Time'],axis=1)
my_balanced_data.head()

V1        V2        V3        V4        V5        V6        V7  \
0 -2.312227  1.951992 -1.609851  3.997906 -0.522188 -1.426545 -2.537387   
1 -3.043541 -3.157307  1.088463  2.288644  1.359805 -1.064823  0.325574   
2 -2.303350  1.759247 -0.359745  2.330243 -0.821628 -0.075788  0.562320   
3 -4.397974  1.358367 -2.592844  2.679787 -1.128131 -1.706536 -3.496197   
4  1.234235  3.019740 -4.304597  4.732795  3.624201 -1.357746  1.713445   

         V8        V9       V10  ...       V20       V21       V22       V23  \
0  1.391657 -2.770089 -2.772272  ...  0.126911  0.517232 -0.035049 -0.465211   
1 -0.067794 -0.270953 -0.838587  ...  2.102339  0.661696  0.435477  1.375966   
2 -0.399147 -0.238253 -1.525412  ... -0.430022 -0.294166 -0.932391  0.172726   
3 -0.248778 -0.247768 -4.801637  ... -0.171608  0.573574  0.176968 -0.436207   
4 -0.496358 -1.282858 -2.447469  ...  0.009061 -0.379068 -0.704181 -0.656805   

        V24       V25       V26       V27       V28  Class  
0  0.320198  0.044519  0.177840  0.261145 -0.143276      1  
1 -0.293803  0.279798 -0.145362 -0.252773  0.035764      1  
2 -0.087330 -0.156114 -0.542628  0.039566 -0.153029      1  
3 -0.053502  0.252405 -0.657488 -0.827136  0.849573      1  
4 -1.632653  1.488901  0.566797 -0.010016  0.146793      1  

[5 rows x 29 columns]

In [13]:
X = my_balanced_data.iloc[:, my_balanced_data.columns != 'Class']
y = my_balanced_data.iloc[:, my_balanced_data.columns == 'Class']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=0)

In [14]:
X_train.shape[0]

688

In [15]:
X_test.shape[0]

296

In [16]:
input_shape = (29, 1)

In [17]:
# Initialising the ANN
model = Sequential()
# Adding the input layer and the first hidden layer
model.add(Dense(units =512 , kernel_initializer = 'uniform', activation = tf.nn.relu, input_dim = 28))
# Adding the second hidden layer
model.add(Dense(units =256 , kernel_initializer = 'uniform', activation = tf.nn.softmax))
# Adding the third hidden layer
model.add(Dense(units = 128, kernel_initializer = 'uniform', activation = tf.nn.relu))
# Adding the output layer
model.add(Dense(units = 1, kernel_initializer = 'uniform', activation = tf.nn.sigmoid))

In [18]:
model.compile(optimizer='Adagrad',  loss='binary_crossentropy',  metrics=['accuracy'])
model.fit(x=X_train,y=y_train, epochs=10)

Epoch 1/10


InternalError:  Blas GEMM launch failed : a.shape=(32, 28), b.shape=(28, 512), m=32, n=512, k=28
	 [[node dense_1/MatMul (defined at C:\Users\QWERTY\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:3009) ]] [Op:__inference_keras_scratch_graph_782]

Function call stack:
keras_scratch_graph


In [ ]:
model.evaluate(X_test, y_test)

In [ ]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)
confusion_matrix(y_test, y_pred)

In [ ]:
print(classification_report(y_test, y_pred))